version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - storykeeper-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=storykeeperdb
      - MONGO_INITDB_ROOT_USERNAME=storykeeperroot
      - MONGO_INITDB_ROOT_PASSWORD=storykeeperpassword

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '9001:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=storykeeperroot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=storykeeperpassword
    depends_on:
      - mongodb
  storykeeper:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: zjdaniels1985/storykeeper-app
    container_name: storykeeper-app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

volumes:
  storykeeper-data: {}

networks:
  default:
    name: storykeeper_network
